server:
  port: 8010
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
<<<<<<< HEAD
      routes:
        - id: ms-sensor-data-collector
          uri: lb://sensor-data-collector
          predicates:
            - Path=/api/v1/sensor-readings/**
          filters:
            - StripPrefix=2
        - id: ms-environmental-analyzer
          uri: lb://environmental-analyzer
          predicates:
            - Path=/api/v1/analyzer/**
          filters:
            - StripPrefix=2
        - id: notification-dispatcher-mock
          uri: lb://notification-dispatcher
          predicates:
            - Path=/api/v1/mock/**
          filters:
            - StripPrefix=2
        - id: notification-dispatcher-notifications
          uri: lb://notification-dispatcher
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - StripPrefix=2
=======
      server:
        webmvc:
          routes:
            - id: ms-sensor-data-collector
              uri: lb://sensor-data-collector
              predicates:
                - Path=/api/v1/sensor-readings/**
              filters:
                - StripPrefix=2
            - id: ms-environmental-analyzer
              uri: lb://environmental-analyzer
              predicates:
                - Path=/api/v1/analyzer/**
              filters:
                - StripPrefix=2
            - id: ms-notification-dispatcher-mock
              uri: lb://notification-dispatcher
              predicates:
                - Path=/api/v1/mock/**
              filters:
                - StripPrefix=2
            - id: ms-notification-dispatcher-notifications
              uri: lb://notification-dispatcher
              predicates:
                - Path=/api/v1/notifications/**
              filters:
                - StripPrefix=2
eureka:
>>>>>>> 6ce5775296e28fdee25b3a9892a2215c4f6db051
    client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${random.value}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
